### ISSUE TITLE
Small parts of corn/wheat act as wall

### ISSUE THREAD

**Issue by NuKuBu-NL** [WALancer/Rosche#276]
or the corn or something els in this field act as a small wall. (its just some small parts of the field noting major.) 
![20181001194326_1](https://user-images.githubusercontent.com/43759163/46305816-c7b24600-c5b2-11e8-915f-9607e5312774.jpg)
![20181001194232_1](https://user-images.githubusercontent.com/43759163/46305817-c7b24600-c5b2-11e8-82c2-39c447eb8337.jpg)
![20181001194259_1](https://user-images.githubusercontent.com/43759163/46305818-c7b24600-c5b2-11e8-89d2-b063b0f0b6bb.jpg)

**Comment by WALancer** [comment]
So the corn/ wheat are working as intended because you can run them over.
![image](https://user-images.githubusercontent.com/3745570/46307640-4e900000-c56c-11e8-9b37-02c0e95c82c0.png)

So there is a geometry object in the middle of each wheat object that is needed so you can run the wheat over. The downside is that you will run into them when running in the wheat field. It is represented by the red outlined pole in the middle. 
![image](https://user-images.githubusercontent.com/3745570/46307764-b21a2d80-c56c-11e8-85a7-b6531486cc86.png)

**Comment by NuKuBu-NL** [comment]
Alright that makes sens, thx for reply

**Comment by AX479** [comment]
I am having a similar issue in Eden mission testing, and with Zeus when placing groups & units. 

Spawned groups & units will not place within the corn field, nor will AI units be able to "path" through the corn while the scenario is running.

AI tanks / vehicles are able to move through the field, just not infantry units.
